# Guard against multiple inclusion
if(DEFINED COMPILER_SETTINGS_INCLUDED)
    return()
endif()
set(COMPILER_SETTINGS_INCLUDED TRUE)

option(BUILD_DEBUG "Build with debug flags" OFF)

set(_COMPILER_COMMON_WARNINGS -Wall -Wextra -Wpedantic)
set(_COMPILER_MSVC_WARNINGS /W4)

function(setup_target_compile_flags TARGET)
    if(NOT TARGET ${TARGET})
        message(FATAL_ERROR "setup_target_compile_flags: target '${TARGET}' does not exist")
    endif()

    target_compile_features(${TARGET} PRIVATE cxx_std_17)
    target_compile_definitions(${TARGET} PRIVATE $<$<BOOL:${BUILD_DEBUG}>:_DEBUG>)

    if(MSVC)
        target_compile_options(${TARGET} PRIVATE ${_COMPILER_MSVC_WARNINGS})
        if(BUILD_DEBUG)
            target_compile_options(${TARGET} PRIVATE /Od /Zi)
        else()
            target_compile_options(${TARGET} PRIVATE /O2)
        endif()
    else()
        target_compile_options(${TARGET} PRIVATE ${_COMPILER_COMMON_WARNINGS})
        if(BUILD_DEBUG)
            target_compile_options(${TARGET} PRIVATE -O0 -g)
        else()
            target_compile_options(${TARGET} PRIVATE -O3)
        endif()
    endif()
endfunction()


function(setup_compiler_specific_options TARGET)
    if(NOT TARGET ${TARGET})
        message(FATAL_ERROR "setup_compiler_specific_options: target '${TARGET}' does not exist")
    endif()

    if(CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
        target_compile_options(${TARGET} PRIVATE ${_COMPILER_COMMON_WARNINGS})
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        target_compile_options(${TARGET} PRIVATE ${_COMPILER_COMMON_WARNINGS})
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        target_compile_options(${TARGET} PRIVATE ${_COMPILER_COMMON_WARNINGS})
    elseif(MSVC)
        target_compile_options(${TARGET} PRIVATE ${_COMPILER_MSVC_WARNINGS})
    else()
        message(WARNING "Unknown compiler: ${CMAKE_CXX_COMPILER_ID}")
    endif()
endfunction()

set(_FORTRAN_COMMON_WARNINGS -Wall -Wextra)
set(_FORTRAN_INTEL_WARNINGS -warn all)

function(setup_fortran_target_compile_flags TARGET)
    if(NOT TARGET ${TARGET})
        message(FATAL_ERROR "setup_fortran_target_compile_flags: target '${TARGET}' does not exist")
    endif()

    if(CMAKE_Fortran_COMPILER_ID STREQUAL "Intel")
        target_compile_options(${TARGET} PRIVATE ${_FORTRAN_INTEL_WARNINGS})
    elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "GNU")
        target_compile_options(${TARGET} PRIVATE ${_FORTRAN_COMMON_WARNINGS})
    elseif(CMAKE_Fortran_COMPILER_ID STREQUAL "Flang")
        target_compile_options(${TARGET} PRIVATE ${_FORTRAN_COMMON_WARNINGS})
    else()
        message(WARNING "Unknown Fortran compiler: ${CMAKE_Fortran_COMPiler_ID}")
    endif()

    if(BUILD_DEBUG)
        target_compile_options(${TARGET} PRIVATE -g)
    else()
        target_compile_options(${TARGET} PRIVATE -O3)
    endif()
endfunction()
